### ISSUE TITLE
Keyframe selection

### ISSUE THREAD

**Issue by mihaibujanca** [haotian-liu/yolact_edge#103]
Hi, thank you for making your work available!

Is it possible to control which frame gets selected as a keyframe (both at train and at test time)? 
Suppose I had a method that evaluates whether or not a frame would make a good keyframe. How would I use it to accept/reject it being used in Yolact Edge?

Thanks!

**Comment by haotian-liu** [comment]
Hi, for your questions, we do not support key frame selection in current code base. So, if you want to use a custom function to select the keyframe, you can do the following:
(1) modify the data loader, so that for a set of the frames, a key frame and a non-key frame is selected and extracted for training;
(2) verify that the output features of the key frame (P4,P5) is stored correctly.

**Comment by mihaibujanca** [comment]
Thanks, I'll close the issue for now and reopen if I have any more questions / possibly open a PR if I get some good results
