### ISSUE TITLE
with tensorrt enabled, model consumes much more gpu memory than it does without

### ISSUE THREAD

**Issue by miba2020** [haotian-liu/yolact_edge#154]
I use your code in industial scene. Thank you very much.

By default eval.py run with tensorrt enabled and in that case it take about 4.9G memory for a 720p video. Disabling tensorrt with --disable_tensorrt will reduce  it to 1.7G. Of course, fps of the former case is higher.

I am expecting the memory usage of tensorrt to be lower.  Sorry is if I am wrong. Then why will this happen? 

By add gc.collect() and torch.cuda.empty_cache after convert_to_tensorrt. The memory usage is still higher, dropping to 3.xG.

Run on jetson xavier NX, unbutu 18.04 jetpack 4.5, cuda 10.2. weight and calib_images downloaded from urls in readme. video sample taken from deepstream sample video. Command line adapted from readme.

ython3 eval.py [--disable_tensorrt] --trained_model=weights/yolact_edge_54_800000.pth --score_threshold=0.3 --top_k=100 --video_multiframe=1 --trt_batch_size 1 --video=sample_720p.mp4

**Comment by 18lalala** [comment]
hello can you tell me your fps on this vedio?

**Comment by miba2020** [comment]
default
Processing FPS: 2.12 | Video Playback FPS: 0.00 | Frames in Buffer: 69

--disable_tensorrt
Processing FPS: 4.80 | Video Playback FPS: 0.00 | Frames in Buffer: 94
Processing FPS: 5.11 | Video Playback FPS: 0.00 | Frames in Buffer: 165

**Comment by haotian-liu** [comment]
Hi, thank you for your interest in this work. Yes, it is possible; since our code base is mainly built for development, for the sake of flexibility, we will **always** load the model no matter the TensorRT modules has been converted or not. Therefore, it is possible that there exists the original PyTorch modules, the TensorRT modules at the same time in the GPU memory (but only one copy will be executed). You need to explicitly handle the loading if you want to save the memory (which shall be definitely doable): you can have a script for converting the TensorRT module; and for each time, you will load the modules separately (whenever the TensorRT module is already converted).

**Comment by miba2020** [comment]
> Hi, thank you for your interest in this work. Yes, it is possible; since our code base is mainly built for development, for the sake of flexibility, we will **always** load the model no matter the TensorRT modules has been converted or not. Therefore, it is possible that there exists the original PyTorch modules, the TensorRT modules at the same time in the GPU memory (but only one copy will be executed). You need to explicitly handle the loading if you want to save the memory (which shall be definitely doable): you can have a script for converting the TensorRT module; and for each time, you will load the modules separately (whenever the TensorRT module is already converted).

Thanks for the explanation/clarification. I will follow your advices. Thank you very much!
