### ISSUE TITLE
Quesions about evaluation FPS

### ISSUE THREAD

**Issue by fanzhemeng** [haotian-liu/yolact_edge#46]
Hi, I was trying to achieve the ~30 fps performance on Xavier you showed [here](https://github.com/haotian-liu/yolact_edge#model-zoo), and tried following different commands.

1. `python3 eval.py --trained_model=weights/yolact_edge_resnet50_54_800000.pth --score_threshold=0.3 --top_k=100 --images=../detect:../detect-output`, with my 1280x1024 images, and I timed each `evalimage` call, each taking ~100ms. It includes time for both detect and generating output images.

   And with `python3 eval.py --trained_model=weights/yolact_edge_resnet50_54_800000.pth --benchmark` with my own validation set of 1280x1024 images, it gives the following output. So this 17.61 fps / 56ms does not include generating output images, is it correct? Because it matchs my timing of line [`preds = net(batch, extras=extras)["pred_outs"]`](https://github.com/haotian-liu/yolact_edge/blob/master/eval.py#L594) in `evalimage`, around 50ms.

   ```
   Processing Images  ██████████████████████████████    472 /    472 (100.00%)    17.61 fps        

   Stats for the last frame:

         Name      | Time (ms)  
   ----------------+------------
     Network Extra |     1.2244 
          backbone |     2.4520 
               fpn |     2.8281 
             proto |     0.8470 
        pred_heads |     3.7948 
        makepriors |     0.0326 
            Detect |    40.6338 
       Postprocess |     3.5093 
              Sync |     0.1154 
   ----------------+------------
             Total |    55.4373 

   Average: 17.61 fps, 56.79 ms
   ```

2. I am using 1280x1024 images, so just to confirm, does resolution affect detection fps for images? I am thinking no as I saw there is resize in code. 

3. To achieve the 30 fps, I also tried videos with `python3 eval.py --trained_model=weights/yolact_edge_resnet50_54_800000.pth --score_threshold=0.3 --top_k=100 --video=../demo-360x640.mp4:../out-demo.mp4`, it gives ~12 fps.

   Then I tried `python3 eval.py --trained_model=weights/yolact_edge_resnet50_54_800000.pth --score_threshold=0.3 --top_k=100 --video_multiframe=2 --trt_batch_size=2 --video=../demo-360x640.mp4:../out-demo.mp4`, it gives ~15 fps. But the output mp4 does not have any detections, I am not sure why but it is currently not my concern.

4. I looked at your paper, and table 1 contains FPS for different precisions. I tried use and not use the `use_fp16_tensorrt` arg in eval.py, there is minor diff in fps for images and did not get me to 30 fps or the 26-27 fps in table 1.

So how can I achieve the 30.7 Xavier fps for YolactEdge with R-50-FPN? Is it for images or videos? It does not include time for generating output images, right?
Much thanks for your work and appreciate any reply!

**Comment by smahesh2694** [comment]
Hi @fanzhemeng, I'm also working on Xavier and I was able to achieve ~30 fps as reported in paper. 

I don't think the image size plays a role here, as all images are resized to `max_size x max_size` by default unless you you modified the `preserve_aspect_ratio` tag to `True` in the base config file [here](https://github.com/haotian-liu/yolact_edge/blob/master/data/config.py#L706).

You may wish to create a custom config by overriding the default values and check if the performance improves. 
Hope you find this useful!

**Comment by haotian-liu** [comment]
@smahesh2694 Thank you for your help.
@fanzhemeng For pure inference speed (which means, the network forwarding and box/mask/class predictions) is not related to image size as @smahesh2694 has said all inputs are resized to `max_size x max_size` if `preserve_aspect_ratio=False`. And it does not include data loading time and mask/box/text **drawing** time. In real-world applications, data loading can be optimized in a buffer with multiple threads to be prepared on GPU beforehand, and drawing can be optimized in a separate thread too. Moreover, the drawing is unnecessary when you use the prediction outputs for downstream tasks for robotics. Thus we are not taking those time into consideration and thus the reported FPS on the paper is the pure inference time.
However, the video processing code / real-time demo reports the real FPS which includes everything, and the mask/box/text drawing happens when you resize the image to the original size. This means that the larger the input is, the longer it takes to draw those masks, and also the longer it takes to copy them from GPU to CPU. This might account for your finding of it being slower on larger images.

**Comment by haotian-liu** [comment]
Closing the issue as the question has been answered and there is no follow-up until now. If you have any more questions or there is anything being unclear, feel free to re-open this issue and post the follow-up thread.

**Comment by fanzhemeng** [comment]
Should put Xavier power mode to `0:MAXN`, from the top right corner on screen. Got desired performance.
